// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNbb7hn-pPG1OZVWeyrtctp0WuwpSecEA',
    appId: '1:668375895241:web:44ac410dd4597959c61118',
    messagingSenderId: '668375895241',
    projectId: 'chat-app-4ef6e',
    authDomain: 'chat-app-4ef6e.firebaseapp.com',
    storageBucket: 'chat-app-4ef6e.appspot.com',
    measurementId: 'G-9QZS2G30P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ1YGlI-hgiMmojn8daASZcocDhJUfIkc',
    appId: '1:668375895241:android:bdfb11e08e7a8623c61118',
    messagingSenderId: '668375895241',
    projectId: 'chat-app-4ef6e',
    storageBucket: 'chat-app-4ef6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD4bnB3XcNtorOAzOF95AfCHATw7YlNYk',
    appId: '1:668375895241:ios:ba94b80839fadf53c61118',
    messagingSenderId: '668375895241',
    projectId: 'chat-app-4ef6e',
    storageBucket: 'chat-app-4ef6e.appspot.com',
    iosClientId: '668375895241-ghcho31rhhurlk1mv2svqg3ebq3prtas.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD4bnB3XcNtorOAzOF95AfCHATw7YlNYk',
    appId: '1:668375895241:ios:ba94b80839fadf53c61118',
    messagingSenderId: '668375895241',
    projectId: 'chat-app-4ef6e',
    storageBucket: 'chat-app-4ef6e.appspot.com',
    iosClientId: '668375895241-ghcho31rhhurlk1mv2svqg3ebq3prtas.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
